#pragma once

#include <string>
#include <unordered_map>

const std::unordered_map<int, std::string> kKeyMap = {{1, "Escape"},
                                               {2, "1"},
                                               {3, "2"},
                                               {4, "3"},
                                               {5, "4"},
                                               {6, "5"},
                                               {7, "6"},
                                               {8, "7"},
                                               {9, "8"},
                                               {10, "9"},
                                               {11, "0"},
                                               {12, "Minus"},
                                               {13, "Equals"},
                                               {14, "Backspace"},
                                               {15, "Tab"},
                                               {16, "Q"},
                                               {17, "W"},
                                               {18, "E"},
                                               {19, "R"},
                                               {20, "T"},
                                               {21, "Y"},
                                               {22, "U"},
                                               {23, "I"},
                                               {24, "O"},
                                               {25, "P"},
                                               {26, "Left Bracket"},
                                               {27, "Right Bracket"},
                                               {28, "Enter"},
                                               {29, "Left Control"},
                                               {30, "A"},
                                               {31, "S"},
                                               {32, "D"},
                                               {33, "F"},
                                               {34, "G"},
                                               {35, "H"},
                                               {36, "J"},
                                               {37, "K"},
                                               {38, "L"},
                                               {39, "Semicolon"},
                                               {40, "Apostrophe"},
                                               {41, "Tilde (Console)"},
                                               {42, "Left Shift"},
                                               {43, "Back Slash"},
                                               {44, "Z"},
                                               {45, "X"},
                                               {46, "C"},
                                               {47, "V"},
                                               {48, "B"},
                                               {49, "N"},
                                               {50, "M"},
                                               {51, "Comma"},
                                               {52, "Period"},
                                               {53, "Forward Slash"},
                                               {54, "Right Shift"},
                                               {55, "NUM*"},
                                               {56, "Left Alt"},
                                               {57, "Spacebar"},
                                               {58, "Caps Lock"},
                                               {59, "F1"},
                                               {60, "F2"},
                                               {61, "F3"},
                                               {62, "F4"},
                                               {63, "F5"},
                                               {64, "F6"},
                                               {65, "F7"},
                                               {66, "F8"},
                                               {67, "F9"},
                                               {68, "F10"},
                                               {69, "Num Lock"},
                                               {70, "Scroll Lock"},
                                               {71, "NUM7"},
                                               {72, "NUM8"},
                                               {73, "NUM9"},
                                               {74, "NUM-"},
                                               {75, "NUM4"},
                                               {76, "NUM5"},
                                               {77, "NUM6"},
                                               {78, "NUM+"},
                                               {79, "NUM1"},
                                               {80, "NUM2"},
                                               {81, "NUM3"},
                                               {82, "NUM0"},
                                               {83, "NUM."},
                                               {87, "F11"},
                                               {88, "F12"},
                                               {156, "NUM Enter"},
                                               {157, "Right Control"},
                                               {181, "NUM/"},
                                               {183, "SysRq / PtrScr"},
                                               {184, "Right Alt"},
                                               {197, "Pause"},
                                               {199, "Home"},
                                               {200, "Up Arrow"},
                                               {201, "PgUp"},
                                               {203, "Left Arrow"},
                                               {205, "Right Arrow"},
                                               {207, "End"},
                                               {208, "Down Arrow"},
                                               {209, "PgDown"},
                                               {210, "Insert"},
                                               {211, "Delete"},
                                               {256, "Left Mouse Button"},
                                               {257, "Right Mouse Button"},
                                               {258, "Middle/Wheel Mouse Button"},
                                               {259, "Mouse Button 3"},
                                               {260, "Mouse Button 4"},
                                               {261, "Mouse Button 5"},
                                               {262, "Mouse Button 6"},
                                               {263, "Mouse Button 7"},
                                               {264, "Mouse Wheel Up"},
                                               {265, "Mouse Wheel Down"},
                                               {266, "DPAD_UP"},
                                               {267, "DPAD_DOWN"},
                                               {268, "DPAD_LEFT"},
                                               {269, "DPAD_RIGHT"},
                                               {270, "START"},
                                               {271, "BACK"},
                                               {272, "LEFT_THUMB"},
                                               {273, "RIGHT_THUMB"},
                                               {274, "LEFT_SHOULDER"},
                                               {275, "RIGHT_SHOULDER"},
                                               {276, "A"},
                                               {277, "B"},
                                               {278, "X"},
                                               {279, "Y"},
                                               {280, "LT"},
                                               {281, "RT"}};